// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CropGenie",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "CropGenie",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.cropPrediction",
            teamIdentifier: "8Y33K34N9R",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("crop.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)